# This file contains example macros to use as a basis for configuring how to
# craft items. Each [[xiv_macro]] corresponds to a specific macro and *must*
# contain a name, durability, and list of actions. max_rlvl, min_rlvl,
# difficulty, and specialist are optional.
#
# Durability is a list of comma-separated durability values the macro can be
# used for. For example, the following would allow the macro to be selected
# for 35 and 40 durability recipes.
#   durability = [ 35, 40 ]
#
# Optional fields supported are
# max_rlvl = <number>
#   - This macro is for recipes with a recipe level <= max_rlvl.
# min_rlvl = <number>
#   - This macro is for recipes with a recipe level >= min_rlvl.
# difficulty = <number>
#   - The listed difficulty of the macro. This is referred to as 'Progress' on
#     garlandtools and Teamcraft, but 'Difficulty' in-game on the recipe.
# specialist = <true|false> (defaults to false)
#   - This macro should only be used of the recipe's job is configured as a specialist
#

[[xiv_macro]]
name = "Eulmore Deliveries"
durability = [ 60, 80 ]
specialist = true
actions = """
/ac Reflect <wait.3>
/ac "Prudent Touch" <wait.3>
/ac Innovation <wait.2>
/ac "Delicate Synthesis" <wait.3>
/ac "Prudent Touch" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Delicate Synthesis" <wait.3>
/ac "Delicate Synthesis" <wait.3>
"""

# This macro will work for any recipe below level 50 of any durability
[[xiv_macro]]
name = "1 - 50 HQ"
rlvl_max = 50
durability = [ 35, 40, 60, 70, 80 ]
actions = """
/ac "Trained Eye" <wait.3>
/ac "Careful Synthesis" <wait.3>
"""
